name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip
      - run: pip install ruff black
      - name: Ruff
        run: ruff check . --output-format=github
      - name: Black (check only)
        run: black --check .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip
      - name: Install deps
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest
      - name: Run tests
        env:
          CA_DB_PATH: ${{ runner.temp }}/ca_storage.db
          PUBKEY_DB_PATH: ${{ runner.temp }}/pubKey_storage.db
          FLASK_ENV: testing
        run: pytest -q
